# Generated by Django 5.0.6 on 2024-05-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupas',
            fields=[
                ('id_roupas', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(max_length=255)),
                ('cor', models.IntegerField()),
            ],
        ),
    ]
