# Generated by Django 5.0.6 on 2024-05-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_roupas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roupas',
            new_name='Roupa',
        ),
    ]
